<?php

if (!defined('ABSPATH') && PHP_SAPI !== 'cli') {
	exit;
}

class Trvlr_Icons
{
	const SYMBOL_PREFIX = 'trvlr-icon-';

	/** @var array<string, array>|null */
	private static $registry = null;

	/** @var array<string, true> */
	private static $used = array();

	public static function icons_dir()
	{
		return TRVLR_PLUGIN_DIR . 'icons';
	}

	public static function registry_path()
	{
		return self::icons_dir() . '/generated/icons.php';
	}

	public static function rebuild()
	{
		$dir = self::icons_dir();
		if (!is_dir($dir)) {
			return array('ok' => false, 'error' => 'icons directory missing', 'count' => 0, 'path' => '');
		}

		$files = glob($dir . '/*.svg');
		if ($files === false) {
			$files = array();
		}

		$icons = array();
		foreach ($files as $file) {
			$slug = strtolower((string) preg_replace('/[^a-z0-9\-]+/', '-', basename($file, '.svg')));
			$slug = trim($slug, '-');
			if ($slug === '') {
				continue;
			}

			$parsed = self::parse_svg_file($file);
			if ($parsed === null) {
				continue;
			}

			$icons[$slug] = $parsed;
		}

		ksort($icons, SORT_STRING);

		$generated_dir = $dir . '/generated';
		if (!is_dir($generated_dir) && !@mkdir($generated_dir, 0755, true) && !is_dir($generated_dir)) {
			return array('ok' => false, 'error' => 'could not create generated directory', 'count' => 0, 'path' => '');
		}

		$path = self::registry_path();
		$export = var_export($icons, true);
		$contents = "<?php\n\n// Auto-generated by scripts/build-icons.php — do not edit.\nreturn " . $export . ";\n";

		if (file_put_contents($path, $contents) === false) {
			return array('ok' => false, 'error' => 'could not write registry', 'count' => 0, 'path' => $path);
		}

		self::$registry = $icons;

		return array(
			'ok'    => true,
			'error' => '',
			'count' => count($icons),
			'path'  => $path,
		);
	}

	private static function parse_svg_file($file)
	{
		$raw = file_get_contents($file);
		if ($raw === false || trim($raw) === '') {
			return null;
		}

		$dom = new DOMDocument();
		$previous = libxml_use_internal_errors(true);
		$loaded = $dom->loadXML($raw);
		libxml_clear_errors();
		libxml_use_internal_errors($previous);

		if (!$loaded || !$dom->documentElement) {
			return null;
		}

		$root = $dom->documentElement;
		if (strtolower($root->tagName) !== 'svg') {
			return null;
		}

		$view_box = $root->getAttribute('viewBox');
		if ($view_box === '') {
			$width = $root->getAttribute('width') ?: '24';
			$height = $root->getAttribute('height') ?: '24';
			$view_box = '0 0 ' . preg_replace('/[^0-9.]/', '', $width) . ' ' . preg_replace('/[^0-9.]/', '', $height);
		}

		self::normalize_paint_attrs($root);

		$attr_keys = array('fill', 'stroke', 'stroke-width', 'stroke-linecap', 'stroke-linejoin');
		$attrs = array();
		foreach ($attr_keys as $key) {
			if ($root->hasAttribute($key)) {
				$attrs[$key] = $root->getAttribute($key);
			}
		}

		$body_parts = array();
		foreach ($root->childNodes as $child) {
			if ($child->nodeType === XML_ELEMENT_NODE) {
				$body_parts[] = $dom->saveXML($child);
			}
		}

		$body = implode('', $body_parts);
		if ($body === '') {
			return null;
		}

		return array(
			'viewBox' => $view_box,
			'attrs'   => $attrs,
			'body'    => $body,
		);
	}

	public static function all()
	{
		if (self::$registry !== null) {
			return self::$registry;
		}

		$path = self::registry_path();
		if (!is_readable($path)) {
			self::$registry = array();
			return self::$registry;
		}

		$data = include $path;
		self::$registry = is_array($data) ? $data : array();
		return self::$registry;
	}

	public static function has($name)
	{
		$name = self::normalize_name($name);
		$all = self::all();
		return $name !== '' && isset($all[$name]);
	}

	public static function file_path($name)
	{
		$name = self::normalize_name($name);
		if ($name === '') {
			return '';
		}
		$path = self::icons_dir() . '/' . $name . '.svg';
		return is_readable($path) ? $path : '';
	}

	public static function file_url($name)
	{
		$name = self::normalize_name($name);
		if ($name === '' || self::file_path($name) === '') {
			return '';
		}
		return TRVLR_PLUGIN_URL . 'icons/' . $name . '.svg';
	}

	public static function css_mask_variables($names = array())
	{
		if (!is_array($names) || empty($names)) {
			return '';
		}

		$css = '';
		foreach ($names as $name) {
			$url = self::file_url($name);
			if ($url === '') {
				continue;
			}
			$slug = self::normalize_name($name);
			$css .= '--trvlr-icon-' . $slug . ': url("' . esc_url($url) . '"); ';
		}

		return $css;
	}

	public static function get($name)
	{
		$name = self::normalize_name($name);
		$all = self::all();
		return ($name !== '' && isset($all[$name])) ? $all[$name] : null;
	}

	public static function symbol_id($name)
	{
		return self::SYMBOL_PREFIX . self::normalize_name($name);
	}

	public static function enqueue($name)
	{
		$name = self::normalize_name($name);
		if ($name === '' || !self::has($name)) {
			return false;
		}
		self::$used[$name] = true;
		return true;
	}

	public static function used()
	{
		return array_keys(self::$used);
	}

	public static function render($name, $use = false, $args = array())
	{
		$icon = self::get($name);
		if ($icon === null) {
			return '';
		}

		$slug = self::normalize_name($name);
		$args = is_array($args) ? $args : array();
		$class = isset($args['class']) ? $args['class'] : '';
		if (is_array($class)) {
			$class = implode(' ', $class);
		}
		$class = trim('trvlr-icon trvlr-icon--' . $slug . ' ' . (string) $class);

		$width = isset($args['width']) ? (string) $args['width'] : '24';
		$height = isset($args['height']) ? (string) $args['height'] : '24';

		$attr_string = self::attrs_to_string($icon['attrs']);
		$view_box = esc_attr($icon['viewBox']);

		if ($use) {
			self::enqueue($slug);
			$href = '#' . self::symbol_id($slug);
			return '<svg class="' . esc_attr($class) . '" xmlns="http://www.w3.org/2000/svg" width="' . esc_attr($width) . '" height="' . esc_attr($height) . '" viewBox="' . $view_box . '" ' . $attr_string . ' aria-hidden="true" focusable="false"><use href="' . esc_attr($href) . '"></use></svg>';
		}

		return '<svg class="' . esc_attr($class) . '" xmlns="http://www.w3.org/2000/svg" width="' . esc_attr($width) . '" height="' . esc_attr($height) . '" viewBox="' . $view_box . '" ' . $attr_string . ' aria-hidden="true" focusable="false">' . $icon['body'] . '</svg>';
	}

	/**
	 * @param bool $all When true, include every registered icon (admin preview).
	 */
	public static function render_sprite($all = false)
	{
		$names = $all ? array_keys(self::all()) : self::used();
		if (empty($names)) {
			return '';
		}

		$symbols = '';
		foreach ($names as $name) {
			$icon = self::get($name);
			if ($icon === null) {
				continue;
			}
			$id = esc_attr(self::symbol_id($name));
			$view_box = esc_attr($icon['viewBox']);
			$attr_string = self::attrs_to_string($icon['attrs']);
			$symbols .= '<symbol id="' . $id . '" viewBox="' . $view_box . '" ' . $attr_string . '>' . $icon['body'] . '</symbol>';
		}

		if ($symbols === '') {
			return '';
		}

		return '<svg xmlns="http://www.w3.org/2000/svg" style="position:absolute;width:0;height:0;overflow:hidden" aria-hidden="true" focusable="false">' . $symbols . '</svg>';
	}

	public static function print_sprite($all = false)
	{
		echo self::render_sprite((bool) $all);
	}

	/**
	 * Full sprite + mask CSS vars for admin surfaces (theme card preview, etc.).
	 *
	 * @return void
	 */
	public static function print_admin_assets()
	{
		self::print_sprite(true);

		$mask = self::css_mask_variables(array_keys(self::all()));
		if ($mask === '') {
			return;
		}

		echo '<style id="trvlr-icon-mask-variables">:root{' . $mask . '}</style>';
	}

	private static function normalize_name($name)
	{
		$name = strtolower(trim((string) $name));
		$name = preg_replace('/[^a-z0-9\-]+/', '-', $name);
		return trim((string) $name, '-');
	}

	private static function attrs_to_string($attrs)
	{
		if (!is_array($attrs) || empty($attrs)) {
			return '';
		}
		$parts = array();
		foreach ($attrs as $key => $value) {
			$parts[] = esc_attr($key) . '="' . esc_attr($value) . '"';
		}
		return implode(' ', $parts);
	}

	private static function normalize_paint_attrs(DOMElement $el)
	{
		foreach (array('fill', 'stroke') as $key) {
			if ($el->hasAttribute($key)) {
				$el->setAttribute($key, self::paint_to_current_color($el->getAttribute($key)));
			}
		}

		foreach ($el->childNodes as $child) {
			if ($child instanceof DOMElement) {
				self::normalize_paint_attrs($child);
			}
		}
	}

	private static function paint_to_current_color($value)
	{
		$normalized = strtolower(preg_replace('/\s+/', '', (string) $value));
		$mono = array(
			'black',
			'white',
			'#000',
			'#000000',
			'#fff',
			'#ffffff',
			'#000000ff',
			'#ffffffff',
			'rgb(0,0,0)',
			'rgb(255,255,255)',
			'rgba(0,0,0,1)',
			'rgba(255,255,255,1)',
		);

		return in_array($normalized, $mono, true) ? 'currentColor' : $value;
	}
}

function trvlr_icon($name, $use = false, $args = array())
{
	return Trvlr_Icons::render($name, (bool) $use, $args);
}

function trvlr_parse_icon_arg($icon, $default_name)
{
	if ($icon === false || $icon === 0 || $icon === '0' || $icon === 'false' || $icon === 'no' || $icon === 'off') {
		return false;
	}

	if ($icon === true || $icon === 1 || $icon === '1' || $icon === 'true' || $icon === 'yes' || $icon === 'on' || $icon === '' || $icon === null) {
		return $default_name;
	}

	$name = is_string($icon) ? $icon : '';
	$name = Trvlr_Icons::has($name) ? $name : $default_name;
	return $name;
}

function trvlr_component_icon($icon, $default_name, $class = '')
{
	$name = trvlr_parse_icon_arg($icon, $default_name);
	if ($name === false) {
		return '';
	}

	return trvlr_icon($name, true, array('class' => $class));
}
